name: ci - docker-build

on:
  workflow_call:
    inputs:
      docker_build_matrix:
        description: "Json matrix for docker build"
        required: true
        type: string
      docker_build_platforms:
        description: "Json matrix for docker build"
        required: true
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.docker_build_matrix) }}

    env:
      GHCR_REPO: ghcr.io/${{ github.repository }}
      DOCKERHUB_REPO: ${{ github.repository }}
      DOCKER_BUILD_SUMMARY: "false"
      arch_type: ${{ matrix.arch_type }}
      docker_build_platforms: ${{ inputs.docker_build_platforms }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.repository.default_branch }}
          persist-credentials: false

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5
        with:
          images: |
            ${{ env.GHCR_REPO }}
            ${{ env.DOCKERHUB_REPO }}

      - name: Login to GHCR
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          cache-binary: false

      - name: Build and push by digest
        id: push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          push: true
          provenance: false
          platforms: ${{ env.docker_build_platforms }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.GHCR_REPO }}:${{ env.arch_type }}
          no-cache: true
          build-args: |
            ARCH=${{ env.arch_type }}
            BASE_URL=https://github.com/${{ github.repository }}/releases/latest/download
            QBT_CROSS_NAME=${{ env.qbt_cross_name }}
